version: '3.8'

services:
  app:
    build: .
    container_name: agua-gas-metering-app
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY} 
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules